### ISSUE TITLE
Submitted Service Request in 24-hour time?

### ISSUE THREAD

**Issue by zingelst** [social-torch/open311-mobile#10]
I submitted an issue after midnight and the issue time shows up as "00:04am" 

![image](https://user-images.githubusercontent.com/15971490/64399572-e62c8700-d036-11e9-9f0e-9f4a47704bcd.png)

**Comment by jpward** [comment]
corrected in https://github.com/social-torch/open311-mobile/commit/fdef0a6cca2151e9f490a8bd46919a9feaec71b9
