### ISSUE TITLE
Clicking on picture in Requests takes you to map view but does not select Map in bottom bar

### ISSUE THREAD

**Issue by zingelst** [social-torch/open311-mobile#22]
Repro:
1. Log in, click "requests"
2. Pick a reqeuest, select the image.
3. Observe that the Map view comes up but Requests is still highlighted in bottom bar
4. Clicking Requests does not go back, need to click off Requests and back on to get back to requests.

**Comment by jpward** [comment]
Fixed in 5f5e8fd3064e924e8555ee0af587b8ca06344fc4
