### ISSUE TITLE
Requests list does not show requests user submitted

### ISSUE THREAD

**Issue by jpward** [social-torch/open311-mobile#25]
Expect we are showing requests from guest not current logged in user

**Comment by zingelst** [comment]
Confirmed that is the case. select_city_common.dart:setMyCity() is the only place getUsers is called. getUsers sets up the CityData().users_resp. If you start the app as "guest", users_resp will have the guest requests in it. If you log in afterwards, we don't seem to make another call to getUsers to fill in the CityData().user_resp with the newly logged in user, so the user_resp stays as guest.

My guess is if you use autoLogIn, the user is set properly before going into setMyCity and you see the proper requests.

I guess in the login we should just make another request to getUsers with the new userID to fill out users_resp properly.

**Comment by schnorea** [comment]
I noticed that after submitting a request it didn't show up in my requests until i had exited the app and restarted cleanly.

**Comment by jpward** [comment]
fixed in 32b482cb23d923a45eefc111c441a24909837913, now we get the list after successful login and after successful new submission.
