### ISSUE TITLE
Using location search on map view crashes app

### ISSUE THREAD

**Issue by zingelst** [social-torch/open311-mobile#3]
To reproduce:
1. Run app, select city.
2. Go to Map view, touch into location box
3. Enter "12345" in location, hit enter (green check)

Emulator version
Name: Nexus_5X_API_29_x86
CPU/ABI: Google APIs Intel Atom (x86)
Target: google_apis [Google APIs] (API level 29)
Skin: nexus_5x

**Comment by jpward** [comment]
Funny enough "12345" actually gives me a valid location...."1234" however crashed the app.  Added in a try catch to get around invalid location, see https://github.com/social-torch/open311-mobile/commit/260df2f8724391cb2ba3b9d7d9b0109db879f7a1
