### ISSUE TITLE
Select City layers multiple settings screen

### ISSUE THREAD

**Issue by zingelst** [social-torch/open311-mobile#4]
1. Run app, go to "Settings"
2. Select City, Choose city, Repeat this a few times
3. Hit Back or <- on title bar, see the settings screen transition out to be replaced with... the settings screen.

Emulator version
Name: Nexus_5X_API_29_x86
CPU/ABI: Google APIs Intel Atom (x86)
Target: google_apis [Google APIs] (API level 29)
Skin: nexus_5x

**Comment by jpward** [comment]
Corrected in https://github.com/social-torch/open311-mobile/commit/c8fb8a41052790947af16db8f184ba400d1611fe
