### ISSUE TITLE
Sign up - Bad registration code message is confusing

### ISSUE THREAD

**Issue by zingelst** [social-torch/open311-mobile#5]
1. Run App, go to Log In, then Sign Up
2. Enter a name, email, password, etc, Hit Register
3. Hit "confirm" on Registration Code with an empty confirm code. Error show regex parsing stuff and is really weird if you're not a programmer :)

Emulator version
Name: Nexus_5X_API_29_x86
CPU/ABI: Google APIs Intel Atom (x86)
Target: google_apis [Google APIs] (API level 29)
Skin: nexus_5x

**Comment by jpward** [comment]
Corrected in https://github.com/social-torch/open311-mobile/commit/d73d3c96fcfae6383388a591052fce59bf3b8fac 

*Note: confirm page now provides the number keyboard so user cannot input letters and we also check for no input.  Using a simulator the user can still add in characters which will show regex error but that is a special case*
